// Additional profanity / sexual / vulgar / violence terms and common evasions.
// The core normalizer in textFilter/server also handles separators and leetspeak,
// so this catalog focuses on lexical variants rather than every possible spelling.
export const PROFANITY_EXTRA = [
  // Variantes peruanas/latinoamericanas de xuxa y evasiones comunes
  'xuxa',
  'xuxas',
  'xuxita',
  'xuxitas',
  'xuxito',
  'xuxitos',
  'xuxitaaa',
  'xuxaaa',
  'xux4',
  'xuxita4',
  'xhuxa',
  'xhuxas',
  'xhuxita',
  'xhuxitas',
  'xhuxha',
  'xhuxhas',
  'xuxa madre',
  'x.u.x.a',
  'x.u.x.a.',
  'x u x a',
  'x-u-x-a',
  'x_u_x_a',
  'x1x4',
  'xhuxh4',
  'xhux4',
  'xuxha',
  'xuxh4',
  'xuxaah',
  'xuxaaaa',
  'ksuxa',
  'kshuxa',
  'xuxit4',
  'xuxitA',
  'xux4s',
  // Perú / Latinoamérica: vulgarismos, modismos y variantes frecuentes
  'pichula','pichulas','pichulón','pichulona','pichulazo','pichulazos','pichulear','pichuleando','pichuleado',
  'pichu','pichu la','pichula','pichul4','p1chula','p1chul4','pichul4zo','pichulazo',
  'pinga','pingas','pingazo','pingazos','pingón','pingona','pingon','pingona','pingar','pinguear',
  'p1nga','p1ng4','pinga','ping4','p1ngazo','p1ng4zo','pingaazo','piinga','pihnga','pinnga','pingga','pingaa','pingaaa',
  'chucha','chuchas','chuchada','chuchadas','chuchazo','chuchazos','chuchón','chuchona','chuchero','chuchera',
  'chuchatumadre','chuchadetumadre','chuchesumadre','chuchasumadre','chuchesumare','chuchatumare','chuchamadre',
  'ctm','ctmr','ctmre','ctmrre','csm','csmr','csmre','csmre','csmrre','csmadre','csmm','ctmm','ctmre',
  'conchatumadre','conchetumadre','conchesumadre','conchasumadre','conchatumare','conchetumare','conchesumare','conchadetumadre',
  'conchade','conchudo','conchuda','conchudos','conchudas','conchaza','conchazo','conchazos','conchita','conchitas',
  'carajo','carajos','carajazo','carajazos','carajudo','carajuda','carajear','carajería','carajeria',
  'mierda','mielda','mierd4','mi3rda','m1erda','m13rda','m3rda','m3rd4','m1erd4','m13rd4','mield4','mierdha','mierlda','mierlhda',
  'mrda','mrd','mrd4','mrdazo','mrdazo','mierdaza','mierdero','mierdera','mierdoso','mierdosa',
  'pendejo','pendeja','pendejos','pendejas','pendejazo','pendejaza','pendejote','pendejota','pendejada','pendejadas','pendejería','pendejeria','pendejez',
  'huevon','huevón','huevona','huevones','huevadas','huevada','huevazo','huevazos','huevudo','huevuda','huevón de mierda','huevonazo','huevonaza',
  'weon','weón','weona','weones','weonas','weonazo','weonaza','weá','wea','webon','webón','webona','webones','webonazo','webonaza',
  'conchudo','conchuda','conchudos','conchudas','conchetumare','conchesumare','conchetumadre',
  'lorna','lornas','lornaazo','lornaza','lornito','lornita','sonso','sonsa','sonsazo','sonsita','zonzo','zonza','zonzazo','zonzita',
  'tarado','tarada','tarados','taradas','taradazo','taradaza','idiota','idiotas','imbecil','imbécil','imbecila','imbécila','imbéciles','estupido','estúpido','estupida','estúpida',
  'cojudo','cojuda','cojudos','cojudas','cojudazo','cojudaza','cojudería','cojuderia','cojudito','cojudita',
  'baboso','babosa','babosos','babosas','babosada','babosadas','babosón','babosona',
  'argollero','argollera','argolleros','argolleras','sobón','sobona','sobones','sobona','lamebotas','lamebotas',
  'lambón','lambona','lambones','lambona','chupamedias','chupamedia','chupamedias','adulón','adulona',
  'maricón','maricon','maricona','mariconazo','marik','marika','marica','marico','maricas','marikón','marikon',
  'cabro','cabros','cabrito','cabrita','cabron','cabrón','cabrona','cabronazo','cabronaza','cabrear','cabreado','cabreada',
  'jodido','jodida','jodidos','jodidas','joder','jódete','jodete','jodiendo','joda','jodas','jodon','jodona','jodón','jodona',
  'puta','puto','putas','putos','putazo','putaza','putería','puteria','putear','puteando','putero','putera','hijoputa','hijueputa','hijuep','hijueputa',
  'ptm','ptmr','pta','pto','ptas','ptos','pvt','pvt4','pvt0','put4','put0','hpt','hpta','hijpt','hdp','hijo de puta','hija de puta',
  'malparido','malparida','malparidos','malparidas','careverga','careculo','carepinga','caremonda','cara de culo','caraeculo','cara de pinga',
  'culero','culera','culeros','culeras','culazo','culazos','culote','culotes','culon','culón','culona','culo','culos','qlo','qla','qlos','qlas','qliao','qliado','ql1','ql0',
  'poto','potos','potón','potona','potazo','potazos','potito','potita','poto peludo',
  'chota','chotas','chotazo','chotazos','chotear','choteando','choteado','chotudo','chotuda','chotearse',
  'panocha','panochas','chocho','chochos','chochazo','chochazos','chochera','cuca','cucas','cucazo','cucaza',
  'tetona','tetonas','tetón','tetona','tetotas','tetaza','tetazas','tetas','teta','pichón','pichona',
  'cachar','kachar','kchar','cach4r','kach4r','kch4r','cachando','cachado','cachada','cachita','cachito','cachar a alguien',
  'culear','culeando','culeado','culeada','culeón','culeona','culeo','culeada','culiar','culiao','culiada','culiando','culiado',
  'cojer','coger','cojida','cojido','cojeme','cógeme','cogeme','cogida','cogido','cogerse','cogiendome','cogiendo',
  'follar','follando','follado','follada','follador','folladora','follón','follona',
  'pajear','pajearse','paja','pajas','pajazo','pajazos','pajilla','pajillas','pajearme','pajeandome',
  'mamada','mamado','mamada','mamar','mame','mámame','mamame','mamón','mamona','mamones','mamonazo','mamonaza','mameluco',
  'chupamela','chupamela','chupame','chupame la','chupamelo','chupalo','chupala','chupapija','chupapolla','chupapollas',
  'soplapollas','soplapolla','soplapija','lameculo','lameculos','lamepoto','lamepinga','lamechucha',
  'violacion','violación','violar','violado','violada','violando','violador','violadora','violal','violah','vi0lar','vi0l4r','v1olar','v1ol4r','vyolar','vyol4r','byolar','biolar',
  'descuartizar','descuartizado','descuartizada','descuartizando','d3scuartizar','d3scuart1zar','dscuartizar','descu4rtizar','descuart1zar',
  'despedazar','desmembrar','mutilar','decapitar','degollar','destripar','apuñalar','apunalar','acuchillar','estrangular','torturar','asesinar','matar',
  // Common abbreviated Peruvian / LATAM forms
  'csm','ctm','ctmr','ctmre','csmr','csmre','tmr','ptm','ptmr','hdp','hpt','hpta','hijpt','ql0','qlo','qla','qlo','mrda','mrd','mrd4','pndj','pnd3j0','wbn','wbn4','weon','weón','weona','webon','webón','cbron','c4bron','vrga','v3rga','vga','p1nga','p1ng4','p1chula','p1chul4','p1j4','p1j4zo','p1j4s','c4ch4r','kch4r','cach4r','d3scuart1z4r','d3sm3mbr4r','mutil4r','d3c4p1t4r','d3g0ll4r','t0rtur4r','4ses1n4r','m4t4r',

  // Spanish vulgar / sexual
  'qlo','ql0','ql a','culazo','culazos','culote','culotes','culon','culona','ojete','ojetes','orto','ortos',
  'concha','conchudo','conchuda','conchudos','conchudas','cojudo','cojuda','cojudazo','cojudaza','coñazo','coñita','coñito',
  'panocha','panochas','chocho','chochos','chucha','chuchas','cuca','cucas','cucota','teton','tetona','tetonas','tetotas',
  'pezon','pezones','nalgas','nalga','nalgon','nalgona','rabo','rabos','pichula','pichulazo','pichulear','pija','pijas','pijazo','pijazos',
  'pijudo','pijuda','poronga','porongas','poronga','chota','chotas','chotazo','chotear','chupapija','chupapijas','chupapolla','chupapollas',
  'pollon','pollona','polla','pollas','pinga','pingas','pingon','pingona','pichinga','pichingas','chucha madre','chuchatumadre','chuchetumadre',
  'cojonazo','cojones','huevudo','huevuda','weonazo','weonaza','webonazo','webonaza','wevos','webos','mamon','mamona','mamones',
  'mamerto','mamerta','lameculos','lameculo','chupamedias','cabronazo','cabronaza','cabronear','cabroneria','cabronería',
  'zorra','zorras','perra','perras','putero','putera','puteros','puteras','puteria','putería','prostituto','prostituta','prostitutas','ramera','rameras',
  'maldito','maldita','malditos','malditas','desgraciado','desgraciada','desgraciados','desgraciadas',
  'estupido','estúpido','estupida','estúpida','cretino','cretina','zopenco','zopenca','zoquete','zoqueta','inepto','inepta',
  'bruto','bruta','ridiculo','ridícula','patetico','patética','imbecila','imbécila','tarada','tarados','taradas',
  'soplapolla','soplapollas','hostia','hostias','hostiaputa','vete a la mierda','vete a la verga','vete a la chucha','anda a la mierda','anda a la verga','anda a la chucha',
  // Common abbreviated/evasive forms
  'mielda','mieldas','mielde','mieldo','mierlda','mierlhda','mrda','m1rd','m3rda','m13rd','m1erda','mi3rda',
  'put4','pvt4','pvt0','pvt','pto','pts','ptas','hdp','hpt','hpta','hijpt','hijuep','nmm','nmms','ntp','csmr','csmre','ctmr','ctmre','ptmr','tmr',
  'vga','vrg','vrga','v3rga','pndjo','pndja','pndejo','pndj','pnd3j0','cbr0n','cbron','c4bron','wbn','wbn4','wbnazo',
  'qla','qlos','qlas','mrd4','q.l.o','q-l-o','q_l_o','ql0','c.u.l.o','c-u-l-o','c_l_o',
  'kchar','kachar','cachar','cach4r','kch4r','cchar','chchar','kchado','kchao','kchando',
  // Porn / explicit
  'pornito','pornitos','pornita','pornitas','polnito','polnitos','polnita','polnitas','pornografia','pornografias','pornografica','pornografico','pornhub','nopor','n0por','n0p0r',
  'p0rno','p0rn0','p0rnogr4fia','p0rn0gr4fia','pornchat','pornochat','pornvideo','pornovideo','pornvideos','videosporno','sexo oral',
  'xxxvideos','contenido porno','peliculas porno','video porno','18+',
  'seso','s3xo','s3x0','sex0',
  // Sexual acts
  'follar','folla','follas','follo','follando','follada','follado','follador','folladora','fornicar','fornicacion','fornicación','fornicaciones',
  'cogerse','cogida','cogidas','cogido','cogidos','tirarse','tirado','tirada','culear','culeada','culeado','culeando','encular','enculado','enculada','encule',
  'masturbarse','masturbando','masturbado','masturbada','masturbador','masturbadora','masturbacion','masturbación','pajearse','pajear','paja','pajas','pajazo','pajazos','pajilla','pajillas',
  'handjob','blowjob','oral',
  // Sexual abuse / violence
  'violar','viola','violó','violado','violada','violando','violacion','violación','violaciones','violador','violadora','violadores','violadoras',
  'violal','violah','vi0lar','vi0l4r','v1olar','v1ol4r','vyolar','vyol4r','vyolarl','biolar','biolal','biolah','byolar','bhyolar',
  'forzar','forzado','forzada','forzando','forzamiento','abusar','abuso','abusado','abusada','abusador','abusadora','abuso sexual','abusar sexualmente',
  'manosear','manoseo','manoseado','tocamiento','tocamientos','acosar','acoso','acosador','acosadora','acosar sexualmente','explotacion sexual','explotación sexual',
  'proxeneta','prostituir','prostitución','pervertido','pervertida','pervertidos','pervertidas','perverso','perversa','degenerado','degenerada','degenerados','degeneradas',
  // Violence / mutilation
  'descuartizar','descuartiza','descuartizado','descuartizada','descuartizando','descuartizamiento','descuartizacion','descuartización',
  'dscuartizar','d3scuartizar','d3scuart1zar','dscuartiz','dscuart','descu4rtizar','descuart1zar',
  'despedazar','despedazado','despedazada','despedazando','d3sp3dazar','dspdzar','dspdz','despdz',
  'desmembrar','desmembrado','desmembrada','desmembrando','desmembramiento','d3sm3mbrar','dsmembrar','dsmembr',
  'mutilar','mutilado','mutilada','mutilando','mutilacion','mutilación','mut1lar','mutil4r','mtilar',
  'decapitar','decapitado','decapitada','decapitando','decapitacion','decapitación','d3capitar','d3cap1tar','dcapitar','dcap',
  'degollar','degollado','degollada','degollando','degollamiento','d3gollar','d3g0llar','dgollar',
  'destripar','destripado','destripada','destripando','destripamiento','d3str1par','dstrpar','dstrp',
  'trocear','troceado','troceada','troceando','acuchillar','acuchillado','acuchillada','apuñalar','apuñalado','apuñalada','apunalar','apunal','4pun4l4r',
  'estrangular','estrangulado','estrangulada','asfixiar','asfixiado','asfixiada','3str4ngul4r','strangular','estrang','torturar','tortura','torturado','torturada','torturando','t0rtur4r','trtur',
  'asesinar','asesino','asesina','asesinado','asesinada','asesinando','asesinato','4ses1nar','ases1nar','as3sin','matar','matame','mátame','matado','matada','m4tar','mtar',
  'muerte','morir','muerete','muérete','suicidar','suicidate','suicidarse','suicidio','asesinate','asesínate',
  'golpear','golpeado','golpeada','golpiza','agredir','agresión','agresor','agresora','amenazar','amenaza','amenazante','intimidar','intimidación',
  'secuestrar','secuestro','secuestrado','secuestrada','raptar','rapto','raptado','raptada','maltratar','maltrato','maltratador','maltratadora',
];

export const PROFANITY_EXTRA_SET = new Set(PROFANITY_EXTRA.map((v) => String(v).trim().toLowerCase()).filter(Boolean));
