import { PROFANITY_EXTRA_SET } from "./profanity-catalog.js";
const LEET_MAP = new Map([
  ["0", "o"],
  ["1", "i"],
  ["!", "i"],
  ["|", "i"],
  ["3", "e"],
  ["4", "a"],
  ["@", "a"],
  ["5", "s"],
  ["7", "t"],
  ["8", "b"],
  ["9", "g"],
  ["6", "g"],
]);

const BLOCKED_WORDS = new Set([
  "culo",
  "culiao",
  "culiada",
  "cagada",
  "cagar",
  "cagon",
  "cagón",
  "caca",
  "kaka",
  "photho",
  "cagona",
  "mierda",
  "mierdas",
  "mierdero",
  "mierderos",
  "mierdoso",
  "mierdosa",
  "mierd",
  "mrd",
  "mierda seca",
  "mierd4",
  "mi3rda",
  "m1erda",
  "m13rda",
  "mierdha",
  "puta",
  "puta madre",
  "puto",
  "putos",
  "putas",
  "putísima",
  "putisima",
  "put4",
  "put0",
  "phuta",
  "phutha",
  "putha",
  "phuto",
  "phutho",
  "putho",
  "phu tha",
  "pu tha",
  "phu-tha",
  "pu-tha",
  "verga",
  "vergas",
  "vergon",
  "vergón",
  "vergota",
  "vergudo",
  "verg4",
  "vrga",
  "v3rga",
  "vergha",
  "v3rg4",
  "pinga",
  "p1nga",
  "pinnga",
  "pingga",
  "pingaa",
  "pingaaa",
  "pin ga",
  "pin-ga",
  "pin.ga",
  "ganpi",
  "gampi",
  "gan pee",
  "gan-pi",
  "piinga",
  "pihnga",
  "pene",
  "nepe",
  "pn",
  "poto",
  "boludo",
  "boluda",
  "boludos",
  "boludas",
  "huevon",
  "huevona",
  "huevones",
  "huevonazo",
  "huevada",
  "huevadas",
  "huevón",
  "weon",
  "weona",
  "weá",
  "wea",
  "weón",
  "webon",
  "webona",
  "webón",
  "webonazo",
  "wey",
  "guey",
  "güey",
  "guei",
  "güei",
  "marica",
  "marico",
  "maricon",
  "maricón",
  "marik",
  "mariko",
  "maricao",
  "marikon",
  "marikón",
  "maric",
  "marikhon",
  "mariquita",
  "marikita",
  "mariqta",
  "mariquitaa",
  "mariquitas",
  "maricha",
  "marikha",
  "maricona",
  "mariconazo",
  "gay",
  "gey",
  "gei",
  "gai",
  "ghey",
  "ghei",
  "g4y",
  "g3y",
  "g@y",
  "cachar",
  "kachar",
  "ca char",
  "ka char",
  "ca-char",
  "ka-char",
  "cchar",
  "kchar",
  "ch char",
  "ch-char",
  "chchar",
  "pendejo",
  "pendeja",
  "pendejos",
  "pendejas",
  "pendejazo",
  "pendejita",
  "idiota",
  "imbecil",
  "imbécil",
  "gilipollas",
  "tonto",
  "tarado",
  "baboso",
  "subnormal",
  "mongol",
  "gonorrea",
  "hijoputa",
  "hijo de puta",
  "hijodeputa",
  "hijueputa",
  "hdp",
  "hp",
  "malparido",
  "malparida",
  "malparío",
  "malparia",
  "careverga",
  "careculo",
  "carepinga",
  "caremonda",
  "pirobo",
  "chupamela",
  "chupamelo",
  "chupame",
  "chu pamela",
  "chu-pamela",
  "mamamela",
  "mamamelo",
  "mamame",
  "conchetumadre",
  "conchasumadre",
  "conchesumadre",
  "conchetumare",
  "conchatumadre",
  "conchetu madre",
  "qlo",
  "qliao",
  "ctmre",
  "csmre",
  "csmr",
  "ctmr",
  "ctm",
  "csm",
  "tmr",
  "ptm",
  "ptmr",
  "pta",
  "zorra",
  "perra",
  "bitch",
  "fuck",
  "shit",
  "asshole",
  "coño",
  "cojon",
  "cojones",
  "joder",
  "jodido",
  "jodida",
  "jodón",
  "jodona",
  "jodete",
  "chingar",
  "chingada",
  "chingado",
  "chingon",
  "chingona",
  "chingón",
  "ching4r",
  "chingad0",
  "mamon",
  "mamón",
  "violar",
  "semen",
  "bcspn",
  "zhemen",
  "cmen",
  "zemen",
  "coji",
  "cojí",
  "cojer",
  "coger",
  "cogi",
  "cogí",
  "cogida",
  "cogido",
  "cogeme",
  "cógeme",
  "teta",
  "tetas",
  "vagina",
  "vaginas",
  "penetrar",
  "penetracion",
  "penetración",
  "sexo",
  "sexual",
  "naco",
  "naca",
  "culero",
  "culera",
  "pinche",
  "pinchis",
  "maricónazo",
  "pito",
  "pene",
  "nepe",
  "pinga",
  "piho",
  "phito",
  "phinga",
  "culo",
  "culos",
  "culitos",
  "culero",
  "culera",
  "culiao",
  "culiada",
  "culh0",
  "culho",
  "teta",
  "tetas",
  "pezon",
  "pezones",
  "teton",
  "tetona",
  "tetonas",
  "vagina",
  "vaginas",
  "vulva",
  "clitoris",
  "clit",
  "anal",
  "ano",
  "ahno",
  "porno",
  "pornografia",
  "pornográfico",
  "pornografico",
  "pornhub",
  "sexo",
  "sexual",
  "semen",
  "masturbar",
  "masturbacion",
  "masturbación",
  "puta",
  "puto",
  "putos",
  "putas",
  "putísima",
  "putisima",
  "put4",
  "put0",
  "phuta",
  "phutha",
  "putha",
  "phuto",
  "phutho",
  "putho",
  "phu tha",
  "pu tha",
  "phu-tha",
  "pu-tha",
  "verga",
  "vergas",
  "vergon",
  "vergón",
  "vergota",
  "vergudo",
  "vrga",
  "v3rga",
  "verg4",
  "vergha",
  "v3rg4",
  "cabro",
  "cabrona",
  "cabrones",
  "cabron",
  "cabronazo",
  "cabroncete",
  "kbro",
  "ca bro",
  "c a b r o",
  "k bro",
  "marica",
  "marico",
  "maricon",
  "maricón",
  "marikon",
  "marik",
  "maric",
  "marikhon",
  "mariquita",
  "marikita",
  "mariqta",
  "mari khon",
  "mari k",
  "mari-k",
  "mari con",
  "mari c on",
  "maricona",
  "mariconazo",
  "gay",
  "gey",
  "gei",
  "gai",
  "ghey",
  "ghei",
  "g4y",
  "g3y",
  "weon",
  "weona",
  "weón",
  "weá",
  "wea",
  "webon",
  "webona",
  "webón",
  "wueon",
  "wueona",
  "guey",
  "güey",
  "guei",
  "güei",
  "huevon",
  "huevón",
  "huevona",
  "huevones",
  "huevonazo",
  "huevada",
  "huevadas",
  "pendejo",
  "pendeja",
  "pendejos",
  "pendejas",
  "pendejazo",
  "pendejita",
  "pinche",
  "pinchis",
  "pajero",
  "pajera",
  "pajear",
  "pajazo",
  "pelotudo",
  "pelotuda",
  "boludo",
  "boluda",
  "forro",
  "gilipollas",
  "capullo",
  "idiota",
  "imbecil",
  "imbécil",
  "tarado",
  "tarada",
  "baboso",
  "babosa",
  "subnormal",
  "mongol",
  "mierda",
  "mierdas",
  "mierdero",
  "mierderos",
  "mierdoso",
  "mierdosa",
  "mierd",
  "mrd",
  "mierda seca",
  "mierd4",
  "mi3rda",
  "m1erda",
  "m13rda",
  "mierdha",
  "cagar",
  "cagada",
  "cagado",
  "cagon",
  "cagón",
  "caca",
  "kaka",
  "photho",
  "cagona",
  "chingar",
  "chingada",
  "chingado",
  "chingon",
  "chingón",
  "chingona",
  "ching4r",
  "chingad0",
  "joder",
  "jodido",
  "jodida",
  "jodón",
  "jodona",
  "jodete",
  "coño",
  "cojon",
  "cojones",
  "coñazo",
  "coñito",
  "cojudo",
  "cojuda",
  "gonorrea",
  "malparido",
  "malparida",
  "malparío",
  "malparia",
  "pirobo",
  "careverga",
  "careculo",
  "carepinga",
  "caremonda",
  "hdp",
  "hp",
  "ctm",
  "ctmr",
  "csm",
  "csmr",
  "ctmre",
  "csmre",
  "tmr",
  "ptm",
  "ptmr",
  "pta",
  "qlo",
  "qliao",
  "hijoputa",
  "hijo de puta",
  "hijodeputa",
  "hijueputa",
  "bitch",
  "fuck",
  "shit",
  "asshole",
  "chucha",
  "chucha madre",
  "chuchamadre",
  "chuchetu mare",
  "chu che tu mare",
  "con che tu mare",
  "conche tu mare",
  "conchetumadre",
  "conchetumare",
  "conchasumadre",
  "conchesumadre",
  "conchetu madre",
  "concha de tu madre",
  "concha tu madre",
  "violar",
  "coger",
  "cojer",
  "cogi",
  "coji",
  "cogido",
  "cogida",
  "cogeme",
  "cógeme",
  "mamon",
  "mamón",
  "mamada",
  "mamame",
  "pajas",
  "pajeros",
  "pajeras",
  "pajeando",
  "pajeo",
  "pajeada",
  "pajita",
  "pajitas",
  "pagear",
  "pageando",
  "pa j e",
  "pa jear",
  "p a j e r o",
  "p a j e a r",
  "p a j a",
  "pa-ja",
  "pa-je",
  "pa-jero",
  "pa-jear",
  'byolar',
  'b.iolar',
  'b yolar',
  'bhyolar',
  'b-yolar',
  'b_yolar',
  'b y o l a r',
  'b.y.o.l.a.r',
  'violar',
  'biolar',
  'v i o l a r',
  'v.i.o.l.a.r',
  'v-yolar',
  'v_yolar',
  'vhyolar',
  'coji',
  'cojí',
  'cojer',
  'cojerse',
  'cojiendo',
  'cojido',
  'cojida',
  'cojan',
  'cojas',
  'cojo',
  'coja',
  'cogi',
  'cogí',
  'coger',
  'cogerse',
  'cogiendo',
  'cogido',
  'cogida',
  'cogeme',
  'cógeme',
  'kche',
  'kches',
  'kchar',
  'kchao',
  'kcharse',
  'kchando',
  'kchado',
  'kchada',
  'cchar',
  'cchao',
  'ccharse',
  'chchar',
  'carajo',
  'carajos',
  'carajito',
  'carajita',
  'carajazo',
  'carajear',
  'chingada madre',
  'chingadamadre',
  'chingadazo',
  'chingadera',
  'chingaderas',
  'chingón',
  'chingona',
  'chingon',
  'chingar',
  'chingue',
  'chingues',
  'chinga',
  'chingas',
  'chingado',
  'chingada',
  'chingados',
  'chingadas',
  'no mames',
  'nomames',
  'mames',
  'mamada',
  'mamadas',
  'mamon',
  'mamón',
  'mamona',
  'mamones',
  'pinche',
  'pinches',
  'pinchi',
  'pinchis',
  'pinche wey',
  'pinchewey',
  'pinche pendejo',
  'pinchependejo',
  'putamadre',
  'puta madre',
  'putazo',
  'putazos',
  'putiza',
  'putizas',
  'putear',
  'puteando',
  'puteo',
  'putero',
  'putera',
  'putón',
  'putona',
  'putones',
  'putonas',
  'putísimo',
  'putisima',
  'putisimo',
  'cabrón',
  'cabrona',
  'cabrones',
  'cabronazo',
  'cabronazos',
  'cabronería',
  'cabroneria',
  'cabronear',
  'cabrón de mierda',
  'cabron de mierda',
  'pendejo',
  'pendeja',
  'pendejos',
  'pendejas',
  'pendejez',
  'pendejada',
  'pendejadas',
  'pendejear',
  'pendejito',
  'pendejita',
  'pendejazo',
  'pendejazos',
  'culero',
  'culera',
  'culeros',
  'culeras',
  'culiado',
  'culiada',
  'culiaos',
  'culiadas',
  'culiao',
  'culiar',
  'culiando',
  'culiadito',
  'culiadita',
  'culo',
  'culos',
  'culote',
  'culotes',
  'culón',
  'culona',
  'verga',
  'vergas',
  'vergazo',
  'vergazos',
  'vergota',
  'vergotas',
  'vergudo',
  'verguero',
  'verguera',
  'vergüenza',
  'vale verga',
  'valeverga',
  'me vale verga',
  'mevaleverga',
  'a la verga',
  'alaverga',
  'pinga',
  'pingazo',
  'pingazos',
  'pingón',
  'pingona',
  'pito',
  'pitos',
  'pichula',
  'pichulazo',
  'pichulear',
  'pija',
  'pijas',
  'pijazo',
  'pijazos',
  'pijudo',
  'pijuda',
  'concha',
  'conchudo',
  'conchuda',
  'conchudos',
  'conchudas',
  'conchatumadre',
  'conchetumadre',
  'conchetumare',
  'conchesumadre',
  'conchasumadre',
  'concha de tu madre',
  'conchadetumadre',
  'chucha',
  'chuchamadre',
  'chucha madre',
  'chuchatumadre',
  'chuchetumadre',
  'chuchetu madre',
  'chucha tu madre',
  'gonorrea',
  'gonorreas',
  'gonorreo',
  'gonorrea hijueputa',
  'pirobo',
  'piroba',
  'pirobo hijueputa',
  'malparido',
  'malparida',
  'malparidos',
  'malparidas',
  'malparición',
  'malparicion',
  'hijueputa',
  'hijueputas',
  'hijueputada',
  'hijoputa',
  'hijos de puta',
  'hijodeputa',
  'hijo de puta',
  'hijuepucha',
  'maricón',
  'maricon',
  'marica',
  'marico',
  'maricas',
  'maricos',
  'maricona',
  'mariconazo',
  'mariconazos',
  'marikón',
  'marikon',
  'mariko',
  'marik',
  'mariquita',
  'marikita',
  'mariqta',
  'boludo',
  'boluda',
  'boludos',
  'boludas',
  'pelotudo',
  'pelotuda',
  'pelotudos',
  'pelotudas',
  'pelotudez',
  'pelotudear',
  'forro',
  'forra',
  'forros',
  'forras',
  'orto',
  'ortudo',
  'ortuda',
  'ortear',
  'la puta que te parió',
  'la puta que te pario',
  'weon',
  'weona',
  'weones',
  'weonas',
  'weón',
  'weónazo',
  'weonazo',
  'webon',
  'webona',
  'webones',
  'webonazo',
  'huevon',
  'huevón',
  'huevona',
  'huevones',
  'huevada',
  'huevadas',
  'huevonazo',
  'huevonazos',
  'huevear',
  'hueveando',
  'hueveo',
  'joder',
  'jodido',
  'jodida',
  'jodidos',
  'jodidas',
  'jodete',
  'jodanse',
  'jódete',
  'no jodas',
  'nojodas',
  'jodón',
  'jodona',
  'jodones',
  'mierda',
  'mierdas',
  'mierdero',
  'mierdera',
  'mierderos',
  'mierderas',
  'mierdoso',
  'mierdosa',
  'mierdón',
  'mierdon',
  'mierdazo',
  'mierdazos',
  'mierdada',
  'mierdadas',
  'mierd4',
  'mi3rda',
  'm1erda',
  'm13rda',
  'mierdha',
  'mrd',
  'mrdas',
  'mrdazo',
  'cagada',
  'cagadas',
  'cagado',
  'cagón',
  'cagona',
  'cagones',
  'cagonas',
  'cagar',
  'cagarse',
  'cagando',
  'cago',
  'cague',
  'cagues',
  'cagón de mierda',
  'cagon de mierda',
  'pajero',
  'pajera',
  'pajeros',
  'pajeras',
  'pajazo',
  'pajazos',
  'pajear',
  'pajeando',
  'pajeo',
  'pajas',
  'pajita',
  'pajitas',
  'idiota',
  'idiotas',
  'imbecil',
  'imbécil',
  'imbeciles',
  'imbéciles',
  'estupido',
  'estúpido',
  'estupida',
  'estúpida',
  'estupidos',
  'estúpidos',
  'tarado',
  'tarada',
  'tarados',
  'taradas',
  'baboso',
  'babosa',
  'babosos',
  'babosas',
  'bruto',
  'bruta',
  'brutos',
  'brutas',
  'zoquete',
  'zoquetes',
  'majadero',
  'majadera',
  'menso',
  'mensa',
  'mensos',
  'mensas',
  'sonso',
  'sonsa',
  'zorra',
  'zorras',
  'perra',
  'perras',
  'perra maldita',
  'perramaldita',
  'maldita',
  'maldito',
  'malditos',
  'malditas',
  'desgraciado',
  'desgraciada',
  'desgraciados',
  'desgraciadas',
  'bastardo',
  'bastarda',
  'bastardos',
  'bastardas',
  'ctm',
  'ctmr',
  'ctmre',
  'csm',
  'csmr',
  'csmre',
  'tmr',
  'ptm',
  'ptmr',
  'pta',
  'qlo',
  'qliao',
  'qlia',
  'hdp',
  'hp',
  'hpt',
  'hpta',
  'nmm',
  'nmms',
  ...PROFANITY_EXTRA_SET,
]);

const SHORT_BLOCKED = new Set(["ctm", "csm", "tmr", "wtf", "xdm", "xdd", "xddd", "kk"]);
const LAUGHTER_UNITS = new Set(["ja", "je", "ji", "jo", "ju", "xa", "xe", "xi", "xo", "xu", "xd"]);

function stripBracketedSegments(value) {
  return String(value ?? "")
    .replace(/\s*\[[^\]]*\]\s*/g, " ")
    .replace(/\s*\([^\)]*\)\s*/g, " ")
    .replace(/\s*\{[^\}]*\}\s*/g, " ")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function stripDiacritics(value) {
  return String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

function stripDiacriticsPreservingEnye(value) {
  const raw = String(value ?? "");
  if (!raw) return "";
  const lower = "__STREAMFUSION_ENYE_LOWER__";
  const upper = "__STREAMFUSION_ENYE_UPPER__";
  return raw
    .replace(/ñ/g, lower)
    .replace(/Ñ/g, upper)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(new RegExp(lower, "g"), "ñ")
    .replace(new RegExp(upper, "g"), "Ñ");
}

function mapLeet(value) {
  let out = "";
  for (const ch of String(value ?? "")) {
    out += LEET_MAP.get(ch) || ch;
  }
  return out;
}

function normalizeForMatch(value) {
  return mapLeet(stripDiacritics(value)).toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function makeProfanityPattern(word) {
  const normalized = normalizeForMatch(word).trim().replace(/\s+/g, " ");
  if (!normalized) return "";
  const collapsed = normalized.replace(/\s+/g, "");
  const core = normalized
    .split(" ")
    .filter(Boolean)
    .map((piece) => piece
      .split("")
      .map((ch, index, arr) => {
        const safe = ch.replace(/[-/\\^$*+?.()|[\\]{}]/g, "\\$&");
        return index < arr.length - 1
          ? `${safe}+[\\s._-]*(?:h+[\\s._-]*)?`
          : `${safe}+`;
      })
      .join(""))
    .join("[\\s._-]+");
  return collapsed.length <= 4
    ? `(^|[^\\p{L}\\p{N}])(?:${core})(?=$|[^\\p{L}\\p{N}])`
    : `(?:${core})`;
}

const PROFANITY_RE = new RegExp([...new Set([...BLOCKED_WORDS].map(makeProfanityPattern).filter(Boolean))].join("|"), "giu");

function censorProfanityText(value) {
  const source = normalizeSpaces(stripBracketedSegments(value));
  if (!source || !PROFANITY_RE) return source;
  return source.replace(PROFANITY_RE, " ");
}

function normalizeSpaces(value) {

  return String(value ?? "")
    .replace(/[\u0000-\u001f\u007f]/g, " ")
    .replace(/[\p{S}\p{P}]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function compressRepeatedLetters(value) {
  return String(value ?? "").replace(/(.)\1{2,}/gi, "$1$1");
}

function compressLaughToken(token, maxRepeats = 3) {
  const raw = String(token ?? "");
  const lower = raw.toLowerCase();
  if (lower.length < 4 || lower.length % 2 !== 0) return raw;

  const pair = lower.slice(0, 2);
  if (!LAUGHTER_UNITS.has(pair)) return raw;

  let repeated = true;
  for (let i = 0; i < lower.length; i += 2) {
    if (lower.slice(i, i + 2) !== pair) {
      repeated = false;
      break;
    }
  }
  if (!repeated) return raw;

  const count = lower.length / 2;
  if (count <= maxRepeats) return raw;
  return pair.repeat(maxRepeats);
}

function isGibberishToken(token) {
  const compact = normalizeForMatch(token);
  if (!compact) return true;
  if (/^\d+$/.test(compact)) return false;
  if (BLOCKED_WORDS.has(compact) || SHORT_BLOCKED.has(compact)) return true;

  const squeezed = compact.replace(/(.)\1+/g, "$1");
  if (BLOCKED_WORDS.has(squeezed) || SHORT_BLOCKED.has(squeezed)) return true;

  const vowelCount = (compact.match(/[aeiou]/g) || []).length;
  if (compact.length >= 6 && vowelCount === 0) return true;
  if (compact.length >= 8 && vowelCount <= 1) return true;
  if (compact.length >= 10 && /[bcdfghjklmnpqrstvwxyz]{6,}/.test(compact)) return true;
  return false;
}

function shouldDropToken(token) {
  const rawToken = String(token ?? "").trim().toLowerCase();
  if (["y", "a", "o", "e", "u"].includes(rawToken)) return false;
  const compact = normalizeForMatch(token);
  if (!compact) return true;
  if (BLOCKED_WORDS.has(compact) || SHORT_BLOCKED.has(compact)) return true;

  const squeezed = compact.replace(/(.)\1+/g, "$1");
  if (BLOCKED_WORDS.has(squeezed) || SHORT_BLOCKED.has(squeezed)) return true;

  if (/^\d+$/.test(compact)) return false;
  return isGibberishToken(compact);
}

function sanitizeWord(token, { maxDigits = 4, maxLaughRepeats = 3, preserveEnye = false } = {}) {
  let value = String(token ?? "").trim();
  if (!value) return "";

  value = preserveEnye ? stripDiacriticsPreservingEnye(value) : stripDiacritics(value);
  value = mapLeet(value);
  value = value.replace(/[^\p{L}\p{N}]+/gu, "");
  if (!value) return "";

  if (/^\d+$/.test(value)) {
    return value.slice(0, Math.max(1, maxDigits));
  }

  const laugh = compressLaughToken(value, maxLaughRepeats);
  if (laugh !== value) {
    return laugh;
  }

  value = compressRepeatedLetters(value);
  if (shouldDropToken(value)) return "";

  if (/\d/.test(value)) {
    value = value.replace(/\d{5,}/g, (match) => match.slice(0, Math.max(1, maxDigits)));
  }

  return value;
}

function sanitizeStreamText(value, options = {}) {
  const maxDigits = Number.isFinite(Number(options.maxDigits)) ? Number(options.maxDigits) : 4;
  const maxLaughRepeats = Number.isFinite(Number(options.maxLaughRepeats)) ? Number(options.maxLaughRepeats) : 3;
  const preserveEnye = Boolean(options.preserveEnye);
  const source = censorProfanityText(value);
  if (!source) return "";

  const tokens = source.split(/\s+/).filter(Boolean);
  const out = [];
  for (const rawToken of tokens) {
    const token = rawToken
      .replace(/^[^\p{L}\p{N}]+/gu, "")
      .replace(/[^\p{L}\p{N}]+$/gu, "");
    if (!token) continue;

    const cleaned = sanitizeWord(token, { maxDigits, maxLaughRepeats, preserveEnye });
    if (cleaned) out.push(cleaned);
  }

  return out.join(" ").replace(/\s{2,}/g, " ").trim();
}

function sanitizeDisplayName(value, fallback = "Usuario") {
  const cleaned = sanitizeStreamText(value, { maxDigits: 4, maxLaughRepeats: 3, preserveEnye: true });
  return cleaned || fallback;
}

function sanitizeSpeechText(value, fallback = "") {
  return sanitizeStreamText(value, { maxDigits: 4, maxLaughRepeats: 3, preserveEnye: true }) || fallback;
}

function sanitizeIdentifier(value, fallback = "") {
  const cleaned = sanitizeStreamText(value, { maxDigits: 4, maxLaughRepeats: 3 });
  return cleaned || fallback;
}

export {
  stripBracketedSegments,
  sanitizeStreamText,
  sanitizeDisplayName,
  sanitizeSpeechText,
  sanitizeIdentifier,
};
